### ISSUE TITLE
Create a paymentcard interface and update user interface.

### ISSUE THREAD

**Issue by aldaineclarke** [aldaineclarke/Amber-Eats-Group25#22]
User interface needs to be updated to show payment options, which should be an array of payment cards not a string.

Payment card interface should have the properties: 
Card number,
Name on Card,
Expiration date,
CVV

**Comment by Dawnz** [comment]
just to clarify, these are the acceptance criteria:
-a user should have a payment card interface array under payment options
-a payment card interface should have the following:
Card number,
Name on Card,
Expiration date,
CVV

**Comment by aldaineclarke** [comment]
Completed on commit: 317b23107c1d5700ceaae9fa11762471a6324d41
