### ISSUE TITLE
Update header to show the Cart and also the cart total 

### ISSUE THREAD

**Issue by aldaineclarke** [aldaineclarke/Amber-Eats-Group25#31]
Header should have a cart icon that navigates to the cart route "/cart"
It should also have a badge to shows the amount of items in the cart.

**Comment by Xante102** [comment]
I'll work on it now

**Comment by aldaineclarke** [comment]
That's great. Thanks

**Comment by aldaineclarke** [comment]
you completed the header? not seeing a pull request

**Comment by aldaineclarke** [comment]
fixes #31 on commit 073f9ecae55f1039e53acae9439be3b0683af3c6
